simplify sbom

diff --git a/frameworks/oep-installer-cli/module/npu_accel/debian b/frameworks/oep-installer-cli/module/npu_accel/debian
--- a/frameworks/oep-installer-cli/module/npu_accel/debian
+++ b/frameworks/oep-installer-cli/module/npu_accel/debian
@@ -69,9 +69,10 @@ debian_40_remove_npu_accel () {
 debian_40_sbom_npu_accel () {
   configure_npu_accel "$@"
   local packages=($(set -o pipefail;curl -fsSL -A Mozilla/5.0 $repository/releases/tags/v$version | jq -r ".assets[] | select(.name|endswith(\"-${ID}${VERSION_ID//./}.tar.gz\")) | .browser_download_url" || curl -fsSL -A Mozilla/5.0 $releases/expanded_assets/v$version | grep -oP 'href="\K/([^"]+/releases/download/[^"]+'$ID${VERSION_ID//./}'.tar.gz)' | sed 's/^/https:\/\/github.com/'))
-  [ ${#packages[*]} -gt 0 ] || return 3
-  cat <<EOF
-$(ensure_sbom_format pkg-list "${packages[@]}")
-EOF
+  [ ${#packages[*]} -gt 0 ] || {
+    echo "Failed to fetch npu_accel latest package" >&2
+    return 3
+  }
+  ensure_sbom_format pkg-list "${packages[@]}"
 }
 
