use panelled output

diff --git a/frameworks/oep-installer-cli/openedge-cli b/frameworks/oep-installer-cli/openedge-cli
--- a/frameworks/oep-installer-cli/openedge-cli
+++ b/frameworks/oep-installer-cli/openedge-cli
@@ -119,44 +119,50 @@ act_helpper () {
 
   # act in sequence
   if [ ${#handles[@]} -gt 0 ]; then
-    logecho () {
-      awk -v n=$1 '{print strftime("%s"),n,$0;fflush()}'
-    }
-    local start_t=$SECONDS reports=() rc=0
-    for handler in $(echo "${handles[*]}" | tr ' ' '\n' | sort $sort_options); do
-      name=$(echo $handler | cut -f4- -d_)
-      if [[ " $* " = *" --dry-run "* ]]; then
-        echo "Invoke $handler with $(act_extract_args $act_name $name $*)" > >(logecho $name)
-      else
-        local start_c=$SECONDS
-        (
-          set -e
-          $handler $(act_extract_args $act_name $name $*)
-        ) > >(logecho $name) 2>&1
-        local rc1=$?
-        reports+=("$name|rc=$rc1|$(( SECONDS - start_c )) seconds")
-        if [ $rc1 -ne 0 ]; then
-          rc=$rc1
-          [[ " $* " = *" --continue "* ]] || break
+    local rc=0
+    {
+      local start_t=$SECONDS reports=() rc=0
+      for handler in $(echo "${handles[*]}" | tr ' ' '\n' | sort $sort_options); do
+        name=$(echo $handler | cut -f4- -d_)
+        if [[ " $* " = *" --dry-run "* ]]; then
+          echo "@@COMP $name"
+          echo "Invoke $handler with $(act_extract_args $act_name $name $*)" 
+          echo "@@OK $name"
+        else
+          local start_c=$SECONDS
+          echo "@@COMP $name"
+          (
+            set -e
+            $handler $(act_extract_args $act_name $name $*)
+          )
+          local rc1=$?
+          if [ $rc1 -eq 0 ]; then
+            echo "@@OK $name"
+          else
+            echo "@@FAIL $name"
+          fi
+          reports+=("$name|rc=$rc1|$(( SECONDS - start_c )) seconds")
+          if [ $rc1 -ne 0 ]; then
+            rc=$rc1
+            [[ " $* " = *" --continue "* ]] || break
+          fi
         fi
+      done
+      local end_t=$SECONDS
+      if [ ${#reports[@]} -gt 0 ]; then
+        echo "@@REPORT SUMMARY"
+        for line in "${reports[@]}"; do
+          if [[ "$line" = *"|rc=0|"* ]]; then
+            echo "$line"
+          else
+            echo -e "${red}$line${reset}"
+          fi
+        done | ensure_columns
+        echo "Total duration: $(( end_t - start_t )) seconds"
       fi
-    done
+    } > >(ensure_panelled_logs) 2>&1
     # wait for background processes
     wait
-    local end_t=$SECONDS
-
-    if [ ${#reports[@]} -gt 0 ]; then
-      echo
-      echo "======== ${act_name^^} REPORT ========"
-      for line in "${reports[@]}"; do
-        if [[ "$line" = *"|rc=0|"* ]]; then
-          echo "$line"
-        else
-          echo -e "${red}$line${reset}"
-        fi
-      done | ensure_columns
-      echo "Total duration: $(( end_t - start_t )) seconds"
-    fi
     return $rc
   else
     echo "Component not found" 1>&2
@@ -270,9 +276,9 @@ subcommand_bootstrap () {
           ;;
         esac
       done
-      cat "$mydir"/common/os-agnostic >> "$rendered"
-      if [ -r "$mydir"/common/${ID_LIKE} ]; then
-        cat "$mydir"/common/${ID_LIKE} >> "$rendered"
+      cat "$mydir"/common/os-agnostic/* >> "$rendered"
+      if [ -d "$mydir"/common/${ID_LIKE} ]; then
+        cat "$mydir"/common/${ID_LIKE}/* >> "$rendered"
       fi
     fi
     for script in "${!scripts[@]}"; do
