move location

diff --git a/frameworks/oep-installer-cli/openedge-cli b/frameworks/oep-installer-cli/openedge-cli
--- a/frameworks/oep-installer-cli/openedge-cli
+++ b/frameworks/oep-installer-cli/openedge-cli
@@ -4,6 +4,7 @@ main () {
   . /etc/os-release
   red="\033[31m" green="\033[32m" yellow="\033[33m" reset="\033[0m"
   installer_name=openedge-cli
+  installer_bin="$HOME/.local/bin/$installer_name"
 
   local _globals=() _cmds=() _args=() cur=-1 v
   for v in "$@"; do
@@ -93,9 +94,8 @@ main () {
 
           [[ " ${_cmds[*]:0:$_i} " = *" setup "* ]] || subcommand_setup "${_globals[@]}"
 
-          local installer="$HOME/.local/bin/$installer_name"
-          [ -x "$installer" ] || {
-            echo -e "${red}$installer not found; run 'setup' first${reset}" 1>&2
+          [ -x "$installer_bin" ] || {
+            echo -e "${red}$installer_bin not found; run 'setup' first${reset}" 1>&2
             return 3
           }
 
@@ -113,7 +113,7 @@ secret="$1"; installer="$2"; shift 2
 rm -f "$secret"
 export SUDO_PASSWORD TF_TOKEN
 exec "$installer" "$@"
-' bash "$_sdir/secrets" "$installer" "${_rest_args[@]}" "${_globals[@]}"
+' bash "$_sdir/secrets" "$installer_bin" "${_rest_args[@]}" "${_globals[@]}"
           _rc=$?
           ensure_tmpdir destroy "$_sdir"
           return $_rc
@@ -135,6 +135,7 @@ subcommand_bootstrap () {
     echo "bootstrap options:"
     echo "  --install=<name>       set default installation component|profile."
     echo "  --start=<name>         set default start component|profile."
+    echo "  --output/-o            specify the output filename [default: $installer_name]."
     echo
     local profiles=($(cd "$mydir";find profile -name "$ID_LIKE" | cut -f2 -d/))
     [ ${#profiles[*]} -eq 0 ] || (
@@ -152,8 +153,36 @@ subcommand_bootstrap () {
     return 0
   fi
   
+  # parse args
+  local install_modules=() start_modules=() modules=() v vlast=""
+  local rendered="$mydir/rendered/$installer_name"
+  for v in "${@}"; do
+    case "$v" in
+    --install=*)
+      install_modules+=(${v#*=})
+      ;;
+    --start=*)
+      start_modules+=(${v#*=})
+      ;;
+    --output|-o)
+      ;;
+    --output=*)
+      rendered="${v#*=}"
+      ;;
+    *)
+      case "$vlast" in
+      --output|-o)
+        rendered="$v"
+        ;;
+      *)
+        modules+=("$v")
+        ;;
+      esac
+    esac
+    vlast="$v"
+  done
+
   # scan for dependencies
-  local modules=(${*##-*})
   [ ${#modules[*]} -gt 0 ] || modules+=($(cd "$mydir";find profile module -name "$ID_LIKE" | cut -f2 -d/))
   modules=(${modules[*]##*/})
   local -A scripts=()
@@ -196,20 +225,8 @@ subcommand_bootstrap () {
     exit 3
   fi
 
-  local rendered="$mydir/rendered/$installer_name"
-  local install_modules=() start_modules=()
   if [[ " $* " != *" --dry-run "* ]]; then
     sed '/^#### COLLECTION OF MODULES ####/q' "$0" > "$rendered"
-    for m in "$@"; do
-      case "$m" in
-      --install=*)
-        install_modules+=(${m#*=})
-        ;;
-      --start=*)
-        start_modules+=(${m#*=})
-        ;;
-      esac
-    done
     cat "$mydir"/common/linux/* >> "$rendered"
     if [ -d "$mydir"/common/${ID_LIKE} ]; then
       cat "$mydir"/common/${ID_LIKE}/* >> "$rendered"
@@ -233,7 +250,7 @@ subcommand_bootstrap () {
     local misc_funcs=($(
       local bfuncs=($(declare -F | cut -f3 -d' '))
       . "$rendered"
-      for f in $(declare -F | grep -v -E " (${ID_LIKE}_[0-9]+|ensure_|act_|subcommand_)" | cut -f3 -d' '); do
+      for f in $(declare -F | grep -v -E " (${ID_LIKE}_[0-9]+|ensure_|act_|verify_|configure_|subcommand_|main)" | cut -f3 -d' '); do
         [[ " ${bfuncs[*]} " = *" $f "* ]] || printf "%s " $f
       done
     ))
diff --git a/frameworks/oep-installer-cli/rendered/openedge-cli b/frameworks/oep-installer-cli/rendered/openedge-cli
--- a/frameworks/oep-installer-cli/rendered/openedge-cli
+++ b/frameworks/oep-installer-cli/rendered/openedge-cli
@@ -4,6 +4,7 @@ main () {
   . /etc/os-release
   red="\033[31m" green="\033[32m" yellow="\033[33m" reset="\033[0m"
   installer_name=openedge-cli
+  installer_bin="$HOME/.local/bin/$installer_name"
 
   local _globals=() _cmds=() _args=() cur=-1 v
   for v in "$@"; do
@@ -93,9 +94,8 @@ main () {
 
           [[ " ${_cmds[*]:0:$_i} " = *" setup "* ]] || subcommand_setup "${_globals[@]}"
 
-          local installer="$HOME/.local/bin/$installer_name"
-          [ -x "$installer" ] || {
-            echo -e "${red}$installer not found; run 'setup' first${reset}" 1>&2
+          [ -x "$installer_bin" ] || {
+            echo -e "${red}$installer_bin not found; run 'setup' first${reset}" 1>&2
             return 3
           }
 
@@ -113,7 +113,7 @@ secret="$1"; installer="$2"; shift 2
 rm -f "$secret"
 export SUDO_PASSWORD TF_TOKEN
 exec "$installer" "$@"
-' bash "$_sdir/secrets" "$installer" "${_rest_args[@]}" "${_globals[@]}"
+' bash "$_sdir/secrets" "$installer_bin" "${_rest_args[@]}" "${_globals[@]}"
           _rc=$?
           ensure_tmpdir destroy "$_sdir"
           return $_rc
@@ -224,17 +224,16 @@ subcommand_setup () {
   [[ " $* " != *" --help "* ]] || return
 
   # reconstruct installer
-  local installer_misc_functions=(amr_setup_osrf_gazebo configure_amr_apt_repo configure_anomalib configure_autonomous_mobile_robot configure_dlstreamer configure_docker configure_esq configure_geti configure_gpu configure_handheld_multi_modal configure_humanoid_imitation_learning configure_libze1 configure_live_video_captioning configure_loitering_detection configure_loss_prevention configure_multimodal_weld_defect_detection configure_multimodal_weld_defect_detection_device configure_multimodal_weld_defect_detection_env configure_nicu_warmer configure_npu configure_openvino configure_order_accuracy configure_osrf_gazebo configure_pallet_defect_detection configure_pcb_anomaly_detection configure_physical_ai_framework configure_physical_ai_studio configure_realsense configure_ros2 configure_ros_openvino configure_smart_intersection configure_smart_parking configure_stationary_robot_vision configure_uv configure_video_search_and_summarization configure_vippet current_multimodal_weld_defect_detection_device generate_multimodal_weld_defect_detection_password generate_multimodal_weld_defect_detection_username multimodal_weld_defect_detection_env_value system_scan_check_cpu_instructions system_scan_check_docker system_scan_check_membank system_scan_check_network_access system_scan_check_pci_device system_scan_get_system_summary verify_amr_apt_repo verify_anomalib verify_autonomous_mobile_robot verify_dlstreamer verify_geti verify_gpu verify_handheld_multi_modal verify_humanoid_imitation_learning verify_live_video_captioning verify_loitering_detection verify_loss_prevention verify_multimodal_weld_defect_detection verify_nicu_warmer verify_npu verify_openvino verify_order_accuracy verify_pallet_defect_detection verify_pcb_anomaly_detection verify_physical_ai_framework verify_physical_ai_studio verify_realsense verify_ros2 verify_ros_openvino verify_smart_intersection verify_smart_parking verify_stationary_robot_vision verify_video_search_and_summarization verify_vippet)
-  local installer="$HOME/.local/bin/$installer_name"
-  mkdir -p "$(dirname "$installer")"
-  cat > "$installer" <<EOF
+  local installer_misc_functions=(amr_setup_osrf_gazebo current_multimodal_weld_defect_detection_device generate_multimodal_weld_defect_detection_password generate_multimodal_weld_defect_detection_username multimodal_weld_defect_detection_env_value system_scan_check_cpu_instructions system_scan_check_docker system_scan_check_membank system_scan_check_network_access system_scan_check_pci_device system_scan_get_system_summary)
+  mkdir -p "$(dirname "$installer_bin")"
+  cat > "$installer_bin" <<EOF
 #!/bin/bash
 $(declare -f ${installer_misc_functions[*]})
-$(declare -f $(declare -F | grep -E " (${ID_LIKE}_[0-9]+_|ensure_|act_|subcommand_|main$)" | cut -f3 -d' ' | tr '\n' ' '))
+$(declare -f $(declare -F | grep -E " (${ID_LIKE}_[0-9]+_|ensure_|act_|verify_|configure_|subcommand_|main$)" | cut -f3 -d' ' | tr '\n' ' '))
 main "\$@"
 EOF
-  chmod a+rx "$installer"
-  echo "Installer reconstructed at $installer"
+  chmod a+rx "$installer_bin"
+  echo "Installer reconstructed at $installer_bin"
 
   # reconstruct bash completion
   local completion_script="$HOME/.local/share/bash-completion/completions/$installer_name"
@@ -1785,7 +1784,7 @@ ensure_ports_open () {
 
 # return the installation path
 ensure_project_path () {
-  echo "$HOME/open-edge-platform"
+  echo "$HOME/.local/open-edge-platform"
 }
 
 
@@ -1832,7 +1831,7 @@ ensure_sudo () {
   else
     # write an askpass helper
     local rundir="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
-    [ -d "$rundir" ] && [ -w "$rundir" ] || rundir="$HOME/.local/state/${installer_name:?}"
+    [ -d "$rundir" ] && [ -w "$rundir" ] || rundir="$(ensure_project_path)/${installer_name:?}"
     mkdir -p "$rundir" 2>/dev/null || return 1
     local askpass_helper="$rundir"/askpass
     (
