Change license action

diff --git a/.github/actions/common/license-namespace-checker/action.yaml b/.github/actions/common/license-namespace-checker/action.yaml
--- a/.github/actions/common/license-namespace-checker/action.yaml
+++ b/.github/actions/common/license-namespace-checker/action.yaml
@@ -1,22 +1,43 @@
 name: 'License and Namespace Checker'
 description: 'Checks license headers and namespace usage in headers'
-inputs:
-  changed_files:
-    description: 'List of changed files to scan'
-    required: true
+# inputs:
+#   changed_files:
+#     description: 'List of changed files to scan'
+#     required: true
 runs:
   using: 'composite'
   steps:
     - name: Check out edge-ai-libraries repository
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
       with:
+        path: edge-ai-libraries-repo
         persist-credentials: false
+
+    - name: Get list of changed files
+      run: |
+        cd edge-ai-libraries-repo
+        if [ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]; then
+          git fetch origin main:main
+          echo "Fetched main branch"
+        fi
+        changed_files=$(git diff --name-only main...$GITHUB_SHA -- '*.h' '*.hpp' '*.c' '*.cpp' '*.sh' '*.py' '*.txt' | grep -E '.*\.(h|hpp|c|cpp|sh|py|txt)$' || true)
+        echo "Performed git diff"
+        if [ -n "$changed_files" ]; then
+          # Add changed files list to the GITHUB_ENV, separated by spaces
+          echo "CHANGED_FILES=$(echo $changed_files)" >> $GITHUB_ENV
+          echo "Changed files:"
+          echo "$changed_files"
+        else
+          # No changed files, explicitly set the exit code to 0
+          echo "No changed files detected."
+          exit 0
+        fi
 
     - name: Check License header and namespace usage in headers
       shell: bash
       run: |
-        if [ -z "${{ inputs.changed_files }}" ]; then
+        if [ -z "${{ env.CHANGED_FILES }}" ]; then
           echo "No new files to scan."
         else
-          ./.github/actions/common/license-namespace-checker/run.sh . ${{ inputs.changed_files }}
+          ./.github/actions/common/license-namespace-checker/run.sh . $CHANGED_FILES
         fi
