rewrite secrets

diff --git a/frameworks/oep-installer-cli/rendered/openedge-cli b/frameworks/oep-installer-cli/rendered/openedge-cli
--- a/frameworks/oep-installer-cli/rendered/openedge-cli
+++ b/frameworks/oep-installer-cli/rendered/openedge-cli
@@ -99,21 +99,22 @@ main () {
             return 3
           }
 
-          local _sdir=""
+          local _sdir="" _sdir_secrets
           ensure_tmpdir create _sdir secrets /dev/shm
-          (umask 077;printf "%s\n%s\n" "$SUDO_PASSWORD" "$TF_TOKEN" > "$_sdir"/secrets)
+          local _sdir_secrets="$_sdir"/secrets
+          (
+            umask 077;
+            for e in SUDOPASSWORD TF_TOKEN HOME USER PATH LOGNAME XDG_RUNTIME_DIR $(compgen -e | grep -E ^OEP_); do
+              printf "export %s=\"%s\"\n" "$e" "${!e}"
+            done > "$_sdir_secrets" || { echo -e "Failed to write secrets"; return 3; }
+          )
           ensure_sudo setpriv --reuid "$(id -u)" --regid "$(id -g)" --groups "$(id -G "$(id -un)" | tr ' ' ',')" \
-            --inh-caps=-all env HOME="$HOME" USER="$(id -un)" LOGNAME="$(id -un)" PATH="$PATH" \
-            XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" OEP_GROUP_REEXEC=1 bash -c '
-secret="$1"; installer="$2"; shift 2
-{
-  IFS= read -r SUDO_PASSWORD
-  IFS= read -r TF_TOKEN
-} < "$secret"
-rm -f "$secret"
-export SUDO_PASSWORD TF_TOKEN
-exec "$installer" "$@"
-' bash "$_sdir/secrets" "$installer_bin" "${_rest_args[@]}" "${_globals[@]}"
+            --inh-caps=-all bash -c '
+secrets="$1"; installer_bin="$2"; shift 2
+. "$secrets"; rm -f "$secrets"
+export OEP_GROUP_REEXEC=1
+exec "$installer_bin" "$@"
+' bash "$_sdir_secrets" "$installer_bin" "${_rest_args[@]}" "${_globals[@]}"
           _rc=$?
           ensure_tmpdir destroy "$_sdir"
           return $_rc
