Add steps if conditions
Signed-off-by: dmichalo <dawid.michalowski@intel.com>

diff --git a/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml b/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
--- a/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
+++ b/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
@@ -156,6 +156,7 @@ jobs:
         # $DLS_PATH/tests/scripts/installation-on-host-entrypoint.sh $DLS_PATH/deb_packages
 
     - name: Test hello_dlstreamer script
+      id: test_hello_dlstreamer_script
       run: |
         mkdir -p $DLS_PATH/test_hello_dlstreamer
         cd $DLS_PATH/test_hello_dlstreamer
@@ -167,19 +168,19 @@ jobs:
             # Check if the file exists and is at least 1kB in size
             if [[ -f "$file" && $(stat --printf="%s" "$file") -ge 1024 ]]; then
                 echo "✅ Valid .mp4 file found: $file"
-                echo "Testing hello_dlstreamer: PASS ✅" >> $GITHUB_STEP_SUMMARY
+                echo "Testing hello_dlstreamer.sh script: PASS ✅" >> $GITHUB_STEP_SUMMARY
                 OUTPUT_FILE_FOUND=1
             fi
         done
         if [[ $OUTPUT_FILE_FOUND -eq 0 ]]; then
             echo "❌ No .mp4 file(s) found or it has less than 1kB size. Exiting..."
-            echo "Testing hello_dlstreamer: FAIL ❌" >> $GITHUB_STEP_SUMMARY
-            exit 1
+            echo "Testing hello_dlstreamer.sh script: FAIL ❌" >> $GITHUB_STEP_SUMMARY
+            # exit 1
         fi
 
     - name: Upload hello_dlstreamer output video
       uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #4.6.2
-      if: always()
+      if: steps.test_hello_dlstreamer_script.outcome == 'success'
       with:
         name: hello_dlstreamer_output_video_${{ matrix.runner_print_label }}_${{ matrix.ubuntu_version }}_CPU_yolo11s
         path: $DLS_PATH/test_hello_dlstreamer
@@ -200,6 +201,7 @@ jobs:
         fi
 
     - name: Run tests
+      id: run_tests
       run: |
         cd $DLS_PATH/tests/functional_tests
         echo "Starting to execute FUNCTIONAL TESTS main sctipt :rocket:"
@@ -207,13 +209,13 @@ jobs:
 
     - name: Upload test results
       uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #4.6.2
-      if: always()
+      if: steps.run_tests.outcome == 'success'
       with:
         name: functional_tests_${{ matrix.runner_print_label }}_on_host_results
         path: "${{ env.DLS_TESTS_RESULTS_PATH }}"
 
     - name: Print tests summary in workflow
-      if: always ()
+      if: steps.run_tests.outcome == 'success'
       run: |
         echo "## Tests summary" >> $GITHUB_STEP_SUMMARY
         sed 's/\[pass\]/:white_check_mark:/g; s/\[\! FAIL \!\]/:x:/g' "${{ env.DLS_TESTS_RESULTS_PATH }}"/functional_tests_${{ matrix.runner_print_label }}_on_host_${{ matrix.ubuntu_version }}_results.txt >> $GITHUB_STEP_SUMMARY
