Enable testing flow
Signed-off-by: dmichalo <dawid.michalowski@intel.com>

diff --git a/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml b/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
--- a/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
+++ b/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
@@ -23,15 +23,15 @@ jobs:
         include:
           - path_dockerfile: $DLS_REL_PATH/docker/ubuntu/ubuntu22.Dockerfile
             ubuntu_version: ubuntu22
-            runner_labels: [ubuntu-24.04-16core-64GB] # Build and run tests on Tiger Lake system with Ubuntu 22
+            runner_labels: [self-hosted, dlstreamer, TGL, ubuntu22] # Build and run tests on Tiger Lake system with Ubuntu 22
             runner_print_label: TGL
           - path_dockerfile: $DLS_REL_PATH/docker/ubuntu/ubuntu24.Dockerfile
             ubuntu_version: ubuntu24
-            runner_labels: [ubuntu-24.04-16core-64GB] # Build and run tests on Tiger Lake system with Ubuntu 24
+            runner_labels: [self-hosted, dlstreamer, TGL, ubuntu24] # Build and run tests on Tiger Lake system with Ubuntu 24
             runner_print_label: TGL
           - path_dockerfile: $DLS_REL_PATH/docker/ubuntu/ubuntu24.Dockerfile
             ubuntu_version: ubuntu24
-            runner_labels: [ubuntu-24.04-16core-64GB] # Build and run tests on Arrow Lake system with Ubuntu 24
+            runner_labels: [self-hosted, dlstreamer, ARL, ubuntu24] # Build and run tests on Arrow Lake system with Ubuntu 24
             runner_print_label: ARL
     steps:
     - name: Check out edge-ai-libraries repository
@@ -91,115 +91,115 @@ jobs:
         timeout: 20m
 
     # ======================================================== OH HOST TESTING PART ========================================================
-    # - name: Check models
-    #   run: |
-    #     if [ -d "${{ env.MODELS_PATH }}" ] && [ "$(ls -A "${{ env.MODELS_PATH }}")" ]; then
-    #       echo "Models: found ✅" >> $GITHUB_STEP_SUMMARY
-    #     else
-    #       echo "Models: folder not found or it is empty ❌" >> $GITHUB_STEP_SUMMARY
-    #       exit 1
-    #     fi
+    - name: Check models
+      run: |
+        if [ -d "${{ env.MODELS_PATH }}" ] && [ "$(ls -A "${{ env.MODELS_PATH }}")" ]; then
+          echo "Models: found ✅" >> $GITHUB_STEP_SUMMARY
+        else
+          echo "Models: folder not found or it is empty ❌" >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
 
-    # - name: Check videos
-    #   run: |
-    #     if [ -d "${{ env.VIDEO_INPUTS_PATH }}" ] && [ "$(ls -A "${{ env.VIDEO_INPUTS_PATH }}")" ]; then
-    #       echo "Tests input videos: found ✅" >> $GITHUB_STEP_SUMMARY
-    #     else
-    #       echo "Tests input videos: folder not found or it is empty ❌" >> $GITHUB_STEP_SUMMARY
-    #       exit 1
-    #     fi
+    - name: Check videos
+      run: |
+        if [ -d "${{ env.VIDEO_INPUTS_PATH }}" ] && [ "$(ls -A "${{ env.VIDEO_INPUTS_PATH }}")" ]; then
+          echo "Tests input videos: found ✅" >> $GITHUB_STEP_SUMMARY
+        else
+          echo "Tests input videos: folder not found or it is empty ❌" >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
 
-    # - name: Install DL Streamer on-host
-    #   run: |
-    #     $DLS_REL_PATH/tests/scripts/installation-on-host-entrypoint.sh $DLS_REL_PATH/deb_packages
+    - name: Install DL Streamer on-host
+      run: |
+        $DLS_REL_PATH/tests/scripts/installation-on-host-entrypoint.sh $DLS_REL_PATH/deb_packages
 
-    # - name: Test hello_dlstreamer script
-    #   id: test_hello_dlstreamer_script
-    #   run: |
-    #     mkdir -p $DLS_REL_PATH/test_hello_dlstreamer
-    #     cd $DLS_REL_PATH/test_hello_dlstreamer
-    #     export MODELS_PATH=${{ env.MODELS_PATH }}
-    #     echo "Running hello_dlstreamer.sh on CPU with model yolo11s"
-    #     /opt/intel/dlstreamer/scripts/hello_dlstreamer.sh --output=file --device=CPU --model=yolo11s
-    #     OUTPUT_FILE_FOUND=0
-    #     for file in *.mp4; do
-    #         # Check if the file exists and is at least 1kB in size
-    #         if [[ -f "$file" && $(stat --printf="%s" "$file") -ge 1024 ]]; then
-    #             echo "✅ Valid .mp4 file found: $file"
-    #             echo "Testing hello_dlstreamer.sh script: PASS ✅" >> $GITHUB_STEP_SUMMARY
-    #             OUTPUT_FILE_FOUND=1
-    #         fi
-    #     done
-    #     if [[ $OUTPUT_FILE_FOUND -eq 0 ]]; then
-    #         echo "❌ No .mp4 file(s) found or it has less than 1kB size. Exiting..."
-    #         echo "Testing hello_dlstreamer.sh script: FAIL ❌" >> $GITHUB_STEP_SUMMARY
-    #         exit 1
-    #     fi
+    - name: Test hello_dlstreamer script
+      id: test_hello_dlstreamer_script
+      run: |
+        mkdir -p $DLS_REL_PATH/test_hello_dlstreamer
+        cd $DLS_REL_PATH/test_hello_dlstreamer
+        export MODELS_PATH=${{ env.MODELS_PATH }}
+        echo "Running hello_dlstreamer.sh on CPU with model yolo11s"
+        /opt/intel/dlstreamer/scripts/hello_dlstreamer.sh --output=file --device=CPU --model=yolo11s
+        OUTPUT_FILE_FOUND=0
+        for file in *.mp4; do
+            # Check if the file exists and is at least 1kB in size
+            if [[ -f "$file" && $(stat --printf="%s" "$file") -ge 1024 ]]; then
+                echo "✅ Valid .mp4 file found: $file"
+                echo "Testing hello_dlstreamer.sh script: PASS ✅" >> $GITHUB_STEP_SUMMARY
+                OUTPUT_FILE_FOUND=1
+            fi
+        done
+        if [[ $OUTPUT_FILE_FOUND -eq 0 ]]; then
+            echo "❌ No .mp4 file(s) found or it has less than 1kB size. Exiting..."
+            echo "Testing hello_dlstreamer.sh script: FAIL ❌" >> $GITHUB_STEP_SUMMARY
+            exit 1
+        fi
 
-    # - name: Upload hello_dlstreamer output video
-    #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #4.6.2
-    #   if: steps.test_hello_dlstreamer_script.outcome == 'success'
-    #   with:
-    #     name: hello_dlstreamer_output_video_${{ matrix.runner_print_label }}_${{ matrix.ubuntu_version }}_CPU_yolo11s
-    #     path: $DLS_REL_PATH/test_hello_dlstreamer
+    - name: Upload hello_dlstreamer output video
+      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #4.6.2
+      if: steps.test_hello_dlstreamer_script.outcome == 'success'
+      with:
+        name: hello_dlstreamer_output_video_${{ matrix.runner_print_label }}_${{ matrix.ubuntu_version }}_CPU_yolo11s
+        path: $DLS_REL_PATH/test_hello_dlstreamer
 
-    # - name: Init tests configurations
-    #   run: |
-    #     if [[ ${{ matrix.runner_print_label }} == "TGL" ]]; then
-    #       echo "TEST_CONFIGS=on_host/samples_TGL.json" >> $GITHUB_ENV
-    #       echo "Selected test configuration file: on_host/samples_TGL.json ✅" >> $GITHUB_STEP_SUMMARY
-    #     elif [[ ${{ matrix.runner_print_label }} == "ARL" ]]; then
-    #       echo "TEST_CONFIGS=on_host/samples_ARL.json" >> $GITHUB_ENV
-    #       echo "Selected test configuration file: on_host/samples_ARL.json ✅" >> $GITHUB_STEP_SUMMARY
-    #     else
-    #       echo "Test configuration file: not found ❌" >> $GITHUB_STEP_SUMMARY
-    #       echo "❌ Cannot assign correct test configuration JSON file for runner based on label: ${{ matrix.runner_print_label }}"
-    #       echo "Please review and fix! Exiting..."
-    #       exit 1
-    #     fi
+    - name: Init tests configurations
+      run: |
+        if [[ ${{ matrix.runner_print_label }} == "TGL" ]]; then
+          echo "TEST_CONFIGS=on_host/samples_TGL.json" >> $GITHUB_ENV
+          echo "Selected test configuration file: on_host/samples_TGL.json ✅" >> $GITHUB_STEP_SUMMARY
+        elif [[ ${{ matrix.runner_print_label }} == "ARL" ]]; then
+          echo "TEST_CONFIGS=on_host/samples_ARL.json" >> $GITHUB_ENV
+          echo "Selected test configuration file: on_host/samples_ARL.json ✅" >> $GITHUB_STEP_SUMMARY
+        else
+          echo "Test configuration file: not found ❌" >> $GITHUB_STEP_SUMMARY
+          echo "❌ Cannot assign correct test configuration JSON file for runner based on label: ${{ matrix.runner_print_label }}"
+          echo "Please review and fix! Exiting..."
+          exit 1
+        fi
 
-    # - name: Init test environemtnt
-    #   run: |
-    #     sudo apt install libcairo2-dev libgirepository1.0-dev
-    #     if [ -d "$HOME/.virtualenvs" ]; then
-    #       echo "Directory $HOME/.virtualenvs exists - removing it"
-    #       rm -rf $HOME/.virtualenvs
-    #     fi
-    #     mkdir -p $HOME/.virtualenvs/dlstreamer
-    #     python3 -m venv $HOME/.virtualenvs/dlstreamer
-    #     $HOME/.virtualenvs/dlstreamer/bin/pip install --no-cache-dir --upgrade pip -r $DLS_REL_PATH/requirements.txt
+    - name: Init test environemtnt
+      run: |
+        sudo apt install libcairo2-dev libgirepository1.0-dev
+        if [ -d "$HOME/.virtualenvs" ]; then
+          echo "Directory $HOME/.virtualenvs exists - removing it"
+          rm -rf $HOME/.virtualenvs
+        fi
+        mkdir -p $HOME/.virtualenvs/dlstreamer
+        python3 -m venv $HOME/.virtualenvs/dlstreamer
+        $HOME/.virtualenvs/dlstreamer/bin/pip install --no-cache-dir --upgrade pip -r $DLS_REL_PATH/requirements.txt
 
-    # - name: Run tests
-    #   id: run_tests
-    #   run: |
-    #     cd $DLS_REL_PATH/tests
-    #     mkdir functional_tests_results
-    #     cd functional_tests_results
-    #     DLS_TESTS_RESULTS_PATH=$PWD
-    #     echo "DLS_TESTS_RESULTS_PATH=$DLS_TESTS_RESULTS_PATH" >> $GITHUB_ENV
-    #     cd ../functional_tests
+    - name: Run tests
+      id: run_tests
+      run: |
+        cd $DLS_REL_PATH/tests
+        mkdir functional_tests_results
+        cd functional_tests_results
+        DLS_TESTS_RESULTS_PATH=$PWD
+        echo "DLS_TESTS_RESULTS_PATH=$DLS_TESTS_RESULTS_PATH" >> $GITHUB_ENV
+        cd ../functional_tests
 
-    #     echo "Starting to execute FUNCTIONAL TESTS main sctipt"
-    #     source $HOME/.virtualenvs/dlstreamer/bin/activate
-    #     ./run_tests.sh --models-path=${{ env.MODELS_PATH }} --video-examples-path=${{ env.VIDEO_INPUTS_PATH }} --test-configs="${{ env.TEST_CONFIGS }}" --results-path="$DLS_TESTS_RESULTS_PATH" --report-name=functional_tests_${{ matrix.runner_print_label }}_on_host_${{ matrix.ubuntu_version }}_results --on-host
+        echo "Starting to execute FUNCTIONAL TESTS main sctipt"
+        source $HOME/.virtualenvs/dlstreamer/bin/activate
+        ./run_tests.sh --models-path=${{ env.MODELS_PATH }} --video-examples-path=${{ env.VIDEO_INPUTS_PATH }} --test-configs="${{ env.TEST_CONFIGS }}" --results-path="$DLS_TESTS_RESULTS_PATH" --report-name=functional_tests_${{ matrix.runner_print_label }}_on_host_${{ matrix.ubuntu_version }}_results --on-host
 
-    # - name: Upload test results
-    #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #4.6.2
-    #   if: steps.run_tests.outcome == 'success'
-    #   with:
-    #     name: functional_tests_${{ matrix.runner_print_label }}_on_host_${{ matrix.ubuntu_version }}_results
-    #     path: "${{ env.DLS_TESTS_RESULTS_PATH }}"
+    - name: Upload test results
+      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #4.6.2
+      if: steps.run_tests.outcome == 'success'
+      with:
+        name: functional_tests_${{ matrix.runner_print_label }}_on_host_${{ matrix.ubuntu_version }}_results
+        path: "${{ env.DLS_TESTS_RESULTS_PATH }}"
 
-    # - name: Print tests summary in workflow
-    #   if: steps.run_tests.outcome == 'success'
-    #   run: |
-    #     echo "## Tests summary" >> $GITHUB_STEP_SUMMARY
-    #     sed 's/\[pass\]/:white_check_mark:/g; s/\[\! FAIL \!\]/:x:/g' "${{ env.DLS_TESTS_RESULTS_PATH }}"/functional_tests_${{ matrix.runner_print_label }}_on_host_${{ matrix.ubuntu_version }}_results.txt >> $GITHUB_STEP_SUMMARY
+    - name: Print tests summary in workflow
+      if: steps.run_tests.outcome == 'success'
+      run: |
+        echo "## Tests summary" >> $GITHUB_STEP_SUMMARY
+        sed 's/\[pass\]/:white_check_mark:/g; s/\[\! FAIL \!\]/:x:/g' "${{ env.DLS_TESTS_RESULTS_PATH }}"/functional_tests_${{ matrix.runner_print_label }}_on_host_${{ matrix.ubuntu_version }}_results.txt >> $GITHUB_STEP_SUMMARY
 
-    # - name: Uninstall dlstreamer
-    #   if: always ()
-    #   run: |
-    #     $DLS_REL_PATH/tests/scripts/uninstall-dlstreamer.sh
+    - name: Uninstall dlstreamer
+      if: always ()
+      run: |
+        $DLS_REL_PATH/tests/scripts/uninstall-dlstreamer.sh
 
     # ======================================================== CLEAUP PART ========================================================
     - name: Clean up
