Add different tests for TGL and ARL
Signed-off-by: Michalowski, Dawid <dawid.michalowski@intel.com>

diff --git a/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml b/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
--- a/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
+++ b/.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
@@ -144,10 +144,26 @@ jobs:
           exit 1
         fi
 
+    - name: Init docker tests configurations
+      run: |
+        if [[ ${{ matrix.runner_print_label }} == "TGL" ]]; then
+          echo "DOCKER_TEST_CONFIGS=docker/aliveness_TGL.json" >> $GITHUB_ENV
+          echo "Selected test configuration file: docker/aliveness_TGL.json ✅" >> $GITHUB_STEP_SUMMARY
+        elif [[ ${{ matrix.runner_print_label }} == "ARL" ]]; then
+          echo "DOCKER_TEST_CONFIGS=docker/aliveness_ARL.json" >> $GITHUB_ENV
+          echo "Selected test configuration file: docker/aliveness_ARL.json ✅" >> $GITHUB_STEP_SUMMARY
+        else
+          echo "Test configuration file: not found ❌" >> $GITHUB_STEP_SUMMARY
+          echo "❌ Cannot assign correct test configuration JSON file for runner based on label: ${{ matrix.runner_print_label }}"
+          echo "Please review and fix! Exiting..."
+          exit 1
+        fi
+
     - name: 🚀 Run Docker tests
       id: run_docker_tests
       env:
         deb_final_testing_img: ghcr.io/${{ github.repository }}/deb-final-testing-img-${{ matrix.ubuntu_version }}:${{ github.sha }}
+        DOCKER_TEST_CONFIGS: ${{ env.DOCKER_TEST_CONFIGS }}
       run: |
         cd $PWD/$DLS_REL_PATH/tests
         mkdir functional_tests_results
@@ -159,7 +175,7 @@ jobs:
         ./run_tests.sh \
           --models-path=${{ env.MODELS_PATH }} \
           --video-examples-path=${{ env.VIDEO_INPUTS_PATH }} \
-          --test-configs="docker/aliveness_tests.json" \
+          --test-configs="$DOCKER_TEST_CONFIGS" \
           --results-path="$DLS_TESTS_RESULTS_PATH" \
           --report-name="DLS_functional_tests_${{ matrix.runner_print_label }}_docker_${{ matrix.ubuntu_version }}_results" \
           --image-name="${deb_final_testing_img}"
@@ -229,10 +245,10 @@ jobs:
     - name: Init on host tests configurations
       run: |
         if [[ ${{ matrix.runner_print_label }} == "TGL" ]]; then
-          echo "TEST_CONFIGS=on_host/samples_TGL.json" >> $GITHUB_ENV
+          echo "HOST_TEST_CONFIGS=on_host/samples_TGL.json" >> $GITHUB_ENV
           echo "Selected test configuration file: on_host/samples_TGL.json ✅" >> $GITHUB_STEP_SUMMARY
         elif [[ ${{ matrix.runner_print_label }} == "ARL" ]]; then
-          echo "TEST_CONFIGS=on_host/samples_ARL.json" >> $GITHUB_ENV
+          echo "HOST_TEST_CONFIGS=on_host/samples_ARL.json" >> $GITHUB_ENV
           echo "Selected test configuration file: on_host/samples_ARL.json ✅" >> $GITHUB_STEP_SUMMARY
         else
           echo "Test configuration file: not found ❌" >> $GITHUB_STEP_SUMMARY
@@ -240,14 +256,6 @@ jobs:
           echo "Please review and fix! Exiting..."
           exit 1
         fi
-
-    # - name: Copy DL Streamer tests repo
-    #   run: |
-    #     cp -r dl-streamer-tests-repo/functional_tests $PWD/$DLS_REL_PATH/tests
-
-    # - name: Link DL Streamer to home directory
-    #   run: |
-    #     ln -s $PWD/$DLS_REL_PATH $HOME
 
     - name: Init host test environemtnt
       run: |
@@ -266,7 +274,7 @@ jobs:
     - name: 🚀 Run on host tests
       id: run_onhost_tests
       env:
-        TEST_CONFIGS: ${{ env.TEST_CONFIGS }}
+        HOST_TEST_CONFIGS: ${{ env.HOST_TEST_CONFIGS }}
       run: |
         cd $PWD/$DLS_REL_PATH/tests
         mkdir functional_tests_results
@@ -279,7 +287,7 @@ jobs:
         ./run_tests.sh \
           --models-path=${{ env.MODELS_PATH }} \
           --video-examples-path=${{ env.VIDEO_INPUTS_PATH }} \
-          --test-configs="$TEST_CONFIGS" \
+          --test-configs="$HOST_TEST_CONFIGS" \
           --results-path="$DLS_TESTS_RESULTS_PATH" \
           --report-name="DLS_functional_tests_${{ matrix.runner_print_label }}_on_host_${{ matrix.ubuntu_version }}_results" \
           --on-host
