Update genai-pre-merge.yaml

diff --git a/.github/workflows/genai-pre-merge.yaml b/.github/workflows/genai-pre-merge.yaml
--- a/.github/workflows/genai-pre-merge.yaml
+++ b/.github/workflows/genai-pre-merge.yaml
@@ -601,3 +601,151 @@ jobs:
           name: bandit-security-report-doc
           path: |
             bandit_scan_report_summary_doc_ing.txt
+
+  
+  video-search-and-summarization-job:
+    needs: detect-changes
+    permissions:
+      contents: read
+    if: contains(fromJson(needs.detect-changes.outputs.changed_projects), 'sample-applications/video-search-and-summarization/')
+    runs-on: ubuntu-22.04-32core-128GB
+    env:
+      HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}   
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          persist-credentials: false   
+      
+      - name: Setup Tools
+        uses: ./.github/actions/setup-tools
+      
+      - name: Run Unit Tests for Core
+        continue-on-error: true
+        shell: bash
+        run: |
+          cd microservices/document-ingestion/pgvector/
+          echo "Running unit test cases"
+          python3.12 -m venv venv
+          source venv/bin/activate
+          poetry install --with dev || true
+          poetry add pytest-html
+          source run.sh --nosetup
+          poetry run pytest tests/unit_tests/ --html=pytest-coverage-doc_ing.html
+          coverage run --source=. -m pytest
+          coverage report -m
+          # Install required packages
+          #poetry add pytest-cov pytest-html 
+          
+          # Run tests with coverage and HTML report in one command
+          #poetry run pytest tests/unit_tests/ --cov=. --cov-report=html --html=pytest-report-doc_ing.html
+          
+          # For a combined coverage and test report
+          #poetry run pytest tests/unit_tests/ --cov=. --cov-report=term --cov-report=html:coverage-html --html=pytest-report-doc_ing.html     
+          deactivate
+          rm -rf venv
+          
+      - name: Upload Coverage Report
+        continue-on-error: true
+        uses: actions/upload-artifact@v4
+        with:
+          name: doc_ing-coverage-report
+          path: |
+            microservices/document-ingestion/pgvector/pytest-coverage-doc_ing.html
+            microservices/document-ingestion/pgvector/pytest-report-doc_ing.html
+            # microservices/document-ingestion/pgvector/htmlcov/index.html
+            # microservices/document-ingestion/pgvector/coverage-html/index.html
+      
+     
+      - name: trivy repo scan
+        continue-on-error: true
+        shell: bash
+        run: |
+          pwd
+          cd microservices/document-ingestion/pgvector/
+          trivy --version
+          trivy image --download-db-only
+          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o trivy-html.tpl
+    
+          # Use the downloaded template
+          trivy fs . --format template --template "@trivy-html.tpl" -o "trivy_code_scan_doc_ing.html"   
+      
+      - name: Upload trivy reports
+        continue-on-error: true
+        uses: actions/upload-artifact@v4
+        if: always()
+        with:
+          name: trivy-code-scan-results-doc_ing
+          path: |
+              microservices/document-ingestion/pgvector/trivy_code_scan_doc_ing.html
+      
+      - name: ClamAV Antivirus Scan
+        continue-on-error: true
+        shell: bash
+        run: |
+          echo "Starting ClamAV scan on sample-applications/chat-question-and-answer/..."
+          
+          docker run --rm \
+            --mount type=bind,source=./microservices/document-ingestion/pgvector/,target=/scandir \
+            clamav/clamav:stable \
+            clamscan --recursive --log=/scandir/clamav-scan-report.log \
+            /scandir
+          
+          SCAN_EXIT_CODE=$?
+          sudo chown $USER:$USER microservices/document-ingestion/pgvector/clamav-scan-report.log 2>/dev/null || true
+          
+          if [ $SCAN_EXIT_CODE -ne 0 ]; then
+            echo "ClamAV scan failed or found issues"
+            exit 1
+          fi
+      
+      - name: Upload Antivirus Report
+        continue-on-error: true
+        if: always()
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
+        with:
+          name: antivirus-report-doc
+          path: microservices/document-ingestion/pgvector/clamav-scan-report.log
+      
+      - name: Trivy Image Scan
+        continue-on-error: true
+        shell: bash
+        run: |
+              echo "print pwd"
+              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o trivy-html.tpl
+              echo "Building image doc_ing-backend and scanning"
+              docker build -f ./microservices/document-ingestion/pgvector/docker/Dockerfile -t doc_ing-backend:latest ./microservices/document-ingestion/pgvector/
+              trivy image doc_ing-backend:latest --ignore-unfixed --format template --template "@trivy-html.tpl" -o microservices/document-ingestion/pgvector/trivy_image_scan_doc_ing.html
+              trivy image --quiet --format spdx-json --output microservices/document-ingestion/pgvector/trivy_image_scan_doc_ing.spdx.json doc_ing-backend:latest
+              echo "completed doc_ing-backend scanning"
+            
+              
+            
+      - name: Upload Trivy Image Report
+        continue-on-error: true
+        if: always()
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
+        with:
+          name: Trivy image scan report-doc
+          path: |
+                microservices/document-ingestion/pgvector/trivy_image_scan_doc_ing.html
+                microservices/document-ingestion/pgvector/trivy_image_scan_doc_ing.spdx.json
+      
+      - name: Run Bandit Security Scan
+        continue-on-error: true
+        shell: bash
+        run: |
+          echo "Running Bandit security scan..."
+          
+          python -m bandit -r microservices/document-ingestion/ -v --exit-zero > bandit_scan_report_summary_doc_ing.txt || echo "Bandit found security issues"
+          
+          echo "Bandit scan completed"
+      
+      - name: Upload Bandit Security Report
+        continue-on-error: true
+        if: always()
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
+        with:
+          name: bandit-security-report-doc
+          path: |
+            bandit_scan_report_summary_doc_ing.txt
